### ISSUE TITLE
Issue with simulated cards in iOS 17

### ISSUE THREAD

**Issue by WadhahEssam** [moyasar/moyasar-ios-sdk#11]
@ahoshaiyan 
Hello Dears at Moyasar, thank you for your amazing work. 

we are migrating from using webview in react native into using the ios sdk and we are having a problem when running apple pay in simulator (iphone 15 / ios 17) 

the error raises after you press on the (pay with passcode) button 

<img width="780" alt="Screenshot 2023-10-07 at 4 51 20 AM" src="https://github.com/moyasar/moyasar-ios-sdk/assets/24798045/37ddccbb-8e4b-4466-a031-a71d3cde62b9">

this is the simulated payment card (happens with both mada and visa supported cards)

<img width="358" alt="Screenshot 2023-10-07 at 4 51 51 AM" src="https://github.com/moyasar/moyasar-ios-sdk/assets/24798045/c4e295e7-b962-464c-a2fc-fd75f02582c4">

looks like issue is coming from this unsafe wrapping, so we can't even catch it when it happens

<img width="532" alt="Screenshot 2023-10-07 at 4 52 47 AM" src="https://github.com/moyasar/moyasar-ios-sdk/assets/24798045/972ca963-45e9-454f-9e70-d86dc855fa08">

🙏

**Comment by aalrayes** [comment]
@WadhahEssam Apple pay tokens are generated by the secure element on Apple devices, making Apple pay transactions on a simulator device will always fail because no token is actually generated.

You can learn more about testing Apple Pay our sandbox environment here:
 https://docs.moyasar.com/apple-pay-testing
  
 and if you're interested in learning how to set up Apple Pay from A-Z, there is a great article on Medium for that:
 https://ali-akhtar.medium.com/working-with-apple-pay-27632ee23482

**Comment by WadhahEssam** [comment]
@aalrayes 

This is true. There is no way you can make this pass since token is not even generated. Thank you friends 🙏🏻
